[functions]
  directory = "netlify/functions"

[build]
  command = "npm run build" # or leave blank if you have no build step
  publish = "."             # ensure it serves from root (where index.html is)
